# https://aka.ms/yaml

name: "$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)"

trigger:
  - master
  - dev

pr:
  - master
  - dev

jobs:
  - job: windows_build

    pool:
      name: Azure Pipelines
      vmImage: 'windows-latest'

    steps:

    - powershell: |
       $sourceDir = "$(Build.SourcesDirectory)".Replace("\", "\\")
       Set-Content -Path $(Build.SourcesDirectory)\sourcelink.json -Value "{ ""documents"": { ""$sourceDir\\*"": ""https://raw.githubusercontent.com/microsoft/BPerf/$(Build.SourceVersion)/*"" } }"
      displayName: 'PowerShell Script'

    - task: CMake@1
      displayName: CMake
      inputs:
        cmakeArgs: '-G "Visual Studio 16 2019" -A x64 $(Build.SourcesDirectory)/CoreCLRProfiler/native/CMakeLists.txt -DLINK_TYPE=Static -DSourceLinkJson=$(Build.SourcesDirectory)\sourcelink.json'

    - task: MSBuild@1
      displayName: 'Build solution CoreCLRProfiler\native\Microsoft.BPerf.CoreCLRProfiler.vcxproj'
      inputs:
        solution: 'CoreCLRProfiler\native\Microsoft.BPerf.CoreCLRProfiler.vcxproj'
        platform: x64
        configuration: RelWithDebInfo

    - publish: $(Build.SourcesDirectory)/CoreCLRProfiler/native/RelWithDebInfo
      artifact: WindowsArtifacts

  - job: linux_build

    pool:
      vmImage: 'ubuntu-18.04'

    variables:
      imageName: 'bperflinux'
      imageTag: '$(build.buildId)'
      fullImageName: '$(imageName):$(imageTag)'

    steps:


    - task: CMake@1
      displayName: CMake
      inputs:
        cmakeArgs: '$(Build.SourcesDirectory)/CoreCLRProfiler/native/CMakeLists.txt'

    - script: |
        cd $(Build.SourcesDirectory)/CoreCLRProfiler/native
        make
      displayName: 'Build code'

    - publish: $(Build.SourcesDirectory)/CoreCLRProfiler/native
      artifact: LinuxArtifacts

  - job: nugetpacking
    dependsOn:
    - windows_build
    - linux_build

    pool:
      vmImage: 'windows-latest'

    steps:

    - download: current
      artifact: LinuxArtifacts

    - download: current
      artifact: WindowsArtifacts

    - task: CopyFiles@2
      displayName: 'Copy Files to: $(Pipeline.Workspace)'
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)'
        Contents: CoreCLRProfiler/managed/Microsoft.BPerf.ProfilerInterop.nuspec
        TargetFolder: '$(Pipeline.Workspace)'

    - task: DotNetCoreCLI@2
      displayName: 'dotnet build'
      inputs:
        projects: 'Microsoft.BPerf.ProfilerInterop.csproj'
        arguments: '-c Release'
        workingDirectory: CoreCLRProfiler/managed

    - task: CopyFiles@2
      displayName: 'Copy Files to: $(Pipeline.Workspace)'
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/CoreCLRProfiler/managed/bin/Release/netstandard2.0'
        Contents: Microsoft.BPerf.ProfilerInterop.dll
        TargetFolder: '$(Pipeline.Workspace)'

    - task: NuGetCommand@2
      displayName: 'Pack Microsoft.BPerf.ProfilerInterop'
      inputs:
        command: pack
        packagesToPack: '$(Pipeline.Workspace)/Microsoft.BPerf.ProfilerInterop.nuspec'
        packDestination: '$(Build.ArtifactStagingDirectory)/NuGetStaging'
        versioningScheme: byBuildNumber

    - task: NuGetCommand@2
      displayName: 'NuGet push to internal feed'
      inputs:
        command: push
        packagesToPush: '$(Build.SourcesDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
        nuGetFeedType: external
        publishFeedCredentials: 'msasg-Bing'
        allowPackageConflicts: true

    - task: NuGetCommand@2
      displayName: 'NuGet push'
      inputs:
        command: push
        packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
        publishVstsFeed: '2d0df07a-afe8-4771-8f48-456a7852cafd/a75f75b3-5627-4efb-a6f9-26c9ae81a223'
        allowPackageConflicts: true